### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by mleczakm**
We are using this library, but encountered few problems when using with current Dbal version - with this fixes works great, as expected ;)

### CODE REVIEW

**Comment by claudiobizzotto** [comment]
Thanks for your PR, @mleczakm! I've updated the package to use the newest version of Doctrine DBAL. Version `0.0.2` is stable—[all tests are passing](https://travis-ci.org/pharako/mysql-dbal), despite what the Packagist icon says. (I guess Packagist takes a while to update its icons.) [Replaced by #6]

**Comment by mleczakm** [comment]
@claudiobizzotto It won't work because this library use private `Dbal\Connection`  `extractTypeValues`, and also call it with wrong data (as you can see in my closed PR, I had to copy this function from Dbal\Connection and replace `$columnName` with `$columnIndex`).

**Comment by claudiobizzotto** [comment]
@mleczakm Could you please open an issue and add an example of a function call?

**Comment by claudiobizzotto** [comment]
Replaced by #7

**Comment by claudiobizzotto** [comment]
@mleczakm Changes were merged and your updates should be working now. Thanks again.

**Pull request closed without merging**
