### PR TITLE
Performance improvement

### LINKED ISSUE #8: Low performance over big data amount
Making `array_merge` in loop results in exponentially increasing computational complexity. I've implemented fix already https://github.com/paruwa/mysql-dbal/commit/a245d0520c76a6b0cbcff8cff6335fd8634168ae (same is needed for inserting) but didn't find time for creating proper PR.

### PR DESCRIPTION
**Pull request by mleczakm**
Fixes #8.
What about releasing new, stable version 1.0.0 after merging this PR? This library works really great on production (with this performance fix of course - without it is very slow for 1000+rows).

### CODE REVIEW

**Comment by claudiobizzotto** [comment]
Thanks for the patch, @mleczakm. These are the results I'm getting from Codeception:

## Inserts

* tag: `0.0.3`
Time: 208 ms, Memory: 10.00 MB
OK (9 tests, 15 assertions)

* `paruwa:performance-improvement`
Time: 223 ms, Memory: 10.00 MB
OK (9 tests, 15 assertions)

## Upserts

* tag: `0.0.3`
Time: 312 ms, Memory: 12.00 MB
OK (29 tests, 51 assertions)

* `paruwa:performance-improvement`
Time: 329 ms, Memory: 12.00 MB
OK (29 tests, 51 assertions)

## Total

* tag: `0.0.3`
Time: 381 ms, Memory: 12.00 MB
OK (38 tests, 66 assertions)

* `paruwa:performance-improvement`
Time: 385 ms, Memory: 12.00 MB
OK (38 tests, 66 assertions)

So, slightly slower overall, but I still need to test with a larger amount of data. Have you had a chance to test for that as well? I'd like to see the results when these tests are run against a more realistic data set.

**Comment by mleczakm** [comment]
@claudiobizzotto This code is working on production for more than year, every second upserting more and more db rows:
obraz
Without this or previous fix (with one array_merge called after loop) it would take at least few seconds. I will fix your tests to check against more than 2 rows and few columns, hope I will find time to do it faster than previous PR.

**Comment by mleczakm** [comment]
Run this as simple comparison:
```
<?php
$array = [];

for ($i = 1; $i <= 1000; $i++) {
    $array[$i] = range(0, $i);
}

$start = microtime(true);

$result = [];
foreach ($array as $internalArray) {
    $result = array_merge($result, $internalArray);
}

$stop = microtime(true);
printf('%f', $stop - $start);
echo "\n";

$start = microtime(true);

$result = [];
foreach ($array as $internalArray) {
    array_push($result, ... $internalArray);
}

$stop = microtime(true);
printf('%f', $stop - $start);
echo "\n";

$start = microtime(true);

$result = [];
foreach ($array as $internalArray) {
    $result[] = $internalArray;
}
$result = array_merge(... $result);

$stop = microtime(true);
printf('%f', $stop - $start);
```
Result from my local dev env:
```
2.703030 #current implementation, with multiple array_merge inside loop 
0.016986 #array_push
0.013540 #one array_merge at the end of loop
```

**Comment by claudiobizzotto** [comment]
I've added a new test file with a large data set and these are the results:

* tag: `0.0.3`
Time: 12.41 seconds, Memory: 96.00 MB
OK (2 tests, 40000 assertions)

* `paruwa:performance-improvement`
Time: 8.35 seconds, Memory: 96.00 MB
OK (2 tests, 40000 assertions)

I'm gonna merge this PR against `development` and add the new _Cest_ file.

**Comment by mleczakm** [comment]
@claudiobizzotto Thanks a lot for merging! I can finally remove my fork from my app dependency :) :+1:

**Pull request merged**
